Sync Explainer.md with Binary.md, add a Subtyping.md
WebAssembly/module-linking pull request #16
Opened 2020-12-02 19:10 UTC by alexcrichton

This commit has a few high-level changes:

* The `Binary.md` is sync'd a bit with `Explainer.md` in terms of
  content and links.
* The textual syntax for `alias` directives was tweaked in
  `Explainer.md` to match `Binary.md`
* Actual section numbers were chosen in the binary format. The exception
  handling proposal uses 13 for an event section so the four new
  sections here are getting 14-17.
* Handling of subtyping between instances and modules is now codified in
  `Subtyping.md`. This goes into more detail about how imports are
  elaborated, how instantiation is expected to work, and how to test for
  subtypes.

This is hoped to describe the intended status quo given the discussion
on #7.

2020-12-02 19:12 UTC, alexcrichton commented
I'm happy to tweak anything here of course! I've attempted to capture the discussion but I may also be missing something here or there, so happy to make changes as necessary.

2020-12-03 21:09 UTC, lukewagner requested changes
Nice job!  In particular:
* Good notes about the subtle interaction between names and indexes into the locally-defined types
* Improving the alias syntax is a great idea.

I requested just a few tiny changes (that I'm open to discussing further) before merging.

2020-12-03 21:09 UTC, lukewagner commented on proposals/module-linking/Subtyping.md
> +Instantiation primarily occurs via name-based resolution (e.g. JS) or
```suggestion
Instantiation primarily occurs via name-based resolution (e.g. in the JS API and other language embeddings) or
```

2020-12-03 21:25 UTC, alexcrichton commented on proposals/module-linking/Explainer.md
> +    (alias $WasiFile parent (type $WasiFile))
Hm if so I'd probably put the `export` in a different spot, like `(alias $i.$f (instance $i) (export (func $f1)))`. My intention was that you'd either parse `parent` or `(instance $i)` to figure out the source of the alias, and then the next part was what you're aliasing. Unless we think something other than exports will be aliased from instances though I'm not sure if we'd want to add `export`.

One alternative though would be to parse either `(parent)` or `(instance $i)` perhaps?

2020-12-03 21:32 UTC, alexcrichton commented on proposals/module-linking/Subtyping.md
> +{imports i1} ≤ {imports i2}              {exports e1} ≤ {exports e2}
Oh nice! Makes sense to me! That also is what I would expect, "one rule to rule them all" with a subtle changeup to make it work.

2020-12-03 21:40 UTC, lukewagner commented on proposals/module-linking/Explainer.md
> +    (alias $WasiFile parent (type $WasiFile))
Yeah, thinking about it again, it does seem sufficiently clear as is.  n/m

2020-12-03 21:51 UTC, alexcrichton commented
Ah yes I really like your suggestion of simplifying the rules, it makes sense to me and looks like it will work out very nicely! I also added some words summarizing the issue's discussion about breaking changes, but if you've got more to add on why a breaking change might be ok I'd be happy to expand that too.

2020-12-03 21:56 UTC, lukewagner approved these changes
Thanks!  @rossberg any comments before merge?

2020-12-04 21:54 UTC, merged

2020-12-08 13:40 UTC, rossberg commented
Sorry for being late. This looks good to me!

Of course, the real fun only starts once we have type imports, which will make various things considerably more complicated and require a number of extensions on aliases, validation etc. There are some pre-existing problems with the proposal that we'll need to fix to be future-proof wrt that, but that's mostly independent of this PR. I'll open issues for those.